# Generated by Django 5.2.1 on 2025-05-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
